package me.redstoner2019.utils;

public enum Setting {
    SET_BOT_DISABLED,
    STABLE_DIFFUSION_ADDRESS,
    NSFW_IN_NSFW_CHANNELS_FORCED,
    USER_BLOCKLIST_ADD,
    USER_BLOCKLIST_REMOVE,
    USER_BLOCKLIST_LIST,
    CHANNELS_DISABLED_ADD,
    CHANNELS_DISABLED_REMOVE,
    CHANNELS_DISABLED_LIST,
    NSFW_CHANNELS_ADD,
    NSFW_CHANNELS_REMOVE,
    NSFW_CHANNELS_LIST,
}
